// Mocks generated by Mockito 5.4.6 from annotations
// in face_box_camera/test/face_box_camera_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;
import 'dart:math' as _i12;
import 'dart:ui' as _i6;

import 'package:camera/camera.dart' as _i3;
import 'package:camera_platform_interface/camera_platform_interface.dart'
    as _i2;
import 'package:face_box_camera/src/services/detection_helper.dart' as _i11;
import 'package:face_box_camera/src/services/mlkit_helper.dart' as _i9;
import 'package:flutter/foundation.dart' as _i5;
import 'package:flutter/material.dart' as _i4;
import 'package:flutter/services.dart' as _i8;
import 'package:google_mlkit_face_detection/google_mlkit_face_detection.dart'
    as _i10;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeCameraDescription_0 extends _i1.SmartFake
    implements _i2.CameraDescription {
  _FakeCameraDescription_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMediaSettings_1 extends _i1.SmartFake implements _i2.MediaSettings {
  _FakeMediaSettings_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCameraValue_2 extends _i1.SmartFake implements _i3.CameraValue {
  _FakeCameraValue_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeXFile_3 extends _i1.SmartFake implements _i2.XFile {
  _FakeXFile_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWidget_4 extends _i1.SmartFake implements _i4.Widget {
  _FakeWidget_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);

  @override
  String toString({_i5.DiagnosticLevel? minLevel = _i5.DiagnosticLevel.info}) =>
      super.toString();
}

class _FakeCameraController_5 extends _i1.SmartFake
    implements _i3.CameraController {
  _FakeCameraController_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRect_6 extends _i1.SmartFake implements _i6.Rect {
  _FakeRect_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [CameraController].
///
/// See the documentation for Mockito's code generation for more information.
class MockCameraController extends _i1.Mock implements _i3.CameraController {
  MockCameraController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CameraDescription get description =>
      (super.noSuchMethod(
            Invocation.getter(#description),
            returnValue: _FakeCameraDescription_0(
              this,
              Invocation.getter(#description),
            ),
          )
          as _i2.CameraDescription);

  @override
  _i2.ResolutionPreset get resolutionPreset =>
      (super.noSuchMethod(
            Invocation.getter(#resolutionPreset),
            returnValue: _i2.ResolutionPreset.low,
          )
          as _i2.ResolutionPreset);

  @override
  bool get enableAudio =>
      (super.noSuchMethod(Invocation.getter(#enableAudio), returnValue: false)
          as bool);

  @override
  _i2.MediaSettings get mediaSettings =>
      (super.noSuchMethod(
            Invocation.getter(#mediaSettings),
            returnValue: _FakeMediaSettings_1(
              this,
              Invocation.getter(#mediaSettings),
            ),
          )
          as _i2.MediaSettings);

  @override
  int get cameraId =>
      (super.noSuchMethod(Invocation.getter(#cameraId), returnValue: 0) as int);

  @override
  _i3.CameraValue get value =>
      (super.noSuchMethod(
            Invocation.getter(#value),
            returnValue: _FakeCameraValue_2(this, Invocation.getter(#value)),
          )
          as _i3.CameraValue);

  @override
  set value(_i3.CameraValue? newValue) => super.noSuchMethod(
    Invocation.setter(#value, newValue),
    returnValueForMissingStub: null,
  );

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void debugCheckIsDisposed() => super.noSuchMethod(
    Invocation.method(#debugCheckIsDisposed, []),
    returnValueForMissingStub: null,
  );

  @override
  _i7.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> prepareForVideoRecording() =>
      (super.noSuchMethod(
            Invocation.method(#prepareForVideoRecording, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> pausePreview() =>
      (super.noSuchMethod(
            Invocation.method(#pausePreview, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> resumePreview() =>
      (super.noSuchMethod(
            Invocation.method(#resumePreview, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> setDescription(_i2.CameraDescription? description) =>
      (super.noSuchMethod(
            Invocation.method(#setDescription, [description]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<_i2.XFile> takePicture() =>
      (super.noSuchMethod(
            Invocation.method(#takePicture, []),
            returnValue: _i7.Future<_i2.XFile>.value(
              _FakeXFile_3(this, Invocation.method(#takePicture, [])),
            ),
          )
          as _i7.Future<_i2.XFile>);

  @override
  _i7.Future<void> startImageStream(_i3.onLatestImageAvailable? onAvailable) =>
      (super.noSuchMethod(
            Invocation.method(#startImageStream, [onAvailable]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> stopImageStream() =>
      (super.noSuchMethod(
            Invocation.method(#stopImageStream, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> startVideoRecording({
    _i3.onLatestImageAvailable? onAvailable,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#startVideoRecording, [], {
              #onAvailable: onAvailable,
            }),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<_i2.XFile> stopVideoRecording() =>
      (super.noSuchMethod(
            Invocation.method(#stopVideoRecording, []),
            returnValue: _i7.Future<_i2.XFile>.value(
              _FakeXFile_3(this, Invocation.method(#stopVideoRecording, [])),
            ),
          )
          as _i7.Future<_i2.XFile>);

  @override
  _i7.Future<void> pauseVideoRecording() =>
      (super.noSuchMethod(
            Invocation.method(#pauseVideoRecording, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> resumeVideoRecording() =>
      (super.noSuchMethod(
            Invocation.method(#resumeVideoRecording, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i4.Widget buildPreview() =>
      (super.noSuchMethod(
            Invocation.method(#buildPreview, []),
            returnValue: _FakeWidget_4(
              this,
              Invocation.method(#buildPreview, []),
            ),
          )
          as _i4.Widget);

  @override
  _i7.Future<double> getMaxZoomLevel() =>
      (super.noSuchMethod(
            Invocation.method(#getMaxZoomLevel, []),
            returnValue: _i7.Future<double>.value(0.0),
          )
          as _i7.Future<double>);

  @override
  _i7.Future<double> getMinZoomLevel() =>
      (super.noSuchMethod(
            Invocation.method(#getMinZoomLevel, []),
            returnValue: _i7.Future<double>.value(0.0),
          )
          as _i7.Future<double>);

  @override
  _i7.Future<void> setZoomLevel(double? zoom) =>
      (super.noSuchMethod(
            Invocation.method(#setZoomLevel, [zoom]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> setFlashMode(_i2.FlashMode? mode) =>
      (super.noSuchMethod(
            Invocation.method(#setFlashMode, [mode]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> setExposureMode(_i2.ExposureMode? mode) =>
      (super.noSuchMethod(
            Invocation.method(#setExposureMode, [mode]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> setExposurePoint(_i6.Offset? point) =>
      (super.noSuchMethod(
            Invocation.method(#setExposurePoint, [point]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<double> getMinExposureOffset() =>
      (super.noSuchMethod(
            Invocation.method(#getMinExposureOffset, []),
            returnValue: _i7.Future<double>.value(0.0),
          )
          as _i7.Future<double>);

  @override
  _i7.Future<double> getMaxExposureOffset() =>
      (super.noSuchMethod(
            Invocation.method(#getMaxExposureOffset, []),
            returnValue: _i7.Future<double>.value(0.0),
          )
          as _i7.Future<double>);

  @override
  _i7.Future<double> getExposureOffsetStepSize() =>
      (super.noSuchMethod(
            Invocation.method(#getExposureOffsetStepSize, []),
            returnValue: _i7.Future<double>.value(0.0),
          )
          as _i7.Future<double>);

  @override
  _i7.Future<double> setExposureOffset(double? offset) =>
      (super.noSuchMethod(
            Invocation.method(#setExposureOffset, [offset]),
            returnValue: _i7.Future<double>.value(0.0),
          )
          as _i7.Future<double>);

  @override
  _i7.Future<void> lockCaptureOrientation([
    _i8.DeviceOrientation? orientation,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#lockCaptureOrientation, [orientation]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> setFocusMode(_i2.FocusMode? mode) =>
      (super.noSuchMethod(
            Invocation.method(#setFocusMode, [mode]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> unlockCaptureOrientation() =>
      (super.noSuchMethod(
            Invocation.method(#unlockCaptureOrientation, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> setFocusPoint(_i6.Offset? point) =>
      (super.noSuchMethod(
            Invocation.method(#setFocusPoint, [point]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  bool supportsImageStreaming() =>
      (super.noSuchMethod(
            Invocation.method(#supportsImageStreaming, []),
            returnValue: false,
          )
          as bool);

  @override
  _i7.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  void removeListener(_i6.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i6.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [MlkitHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockMlkitHelper extends _i1.Mock implements _i9.MlkitHelper {
  MockMlkitHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i2.CameraDescription> get cameras =>
      (super.noSuchMethod(
            Invocation.getter(#cameras),
            returnValue: <_i2.CameraDescription>[],
          )
          as List<_i2.CameraDescription>);

  @override
  _i3.CameraController get cameraController =>
      (super.noSuchMethod(
            Invocation.getter(#cameraController),
            returnValue: _FakeCameraController_5(
              this,
              Invocation.getter(#cameraController),
            ),
          )
          as _i3.CameraController);

  @override
  _i7.Future<_i10.Face?> processCameraImage(_i3.CameraImage? image) =>
      (super.noSuchMethod(
            Invocation.method(#processCameraImage, [image]),
            returnValue: _i7.Future<_i10.Face?>.value(),
          )
          as _i7.Future<_i10.Face?>);

  @override
  _i6.Rect scaleRectPreviewToScreen(
    _i6.Rect? faceBox,
    _i6.Size? previewSize,
    _i6.Size? screenSize,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#scaleRectPreviewToScreen, [
              faceBox,
              previewSize,
              screenSize,
            ]),
            returnValue: _FakeRect_6(
              this,
              Invocation.method(#scaleRectPreviewToScreen, [
                faceBox,
                previewSize,
                screenSize,
              ]),
            ),
          )
          as _i6.Rect);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [DetectionHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockDetectionHelper extends _i1.Mock implements _i11.DetectionHelper {
  MockDetectionHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Rect get limitBoxCoordinate =>
      (super.noSuchMethod(
            Invocation.getter(#limitBoxCoordinate),
            returnValue: _FakeRect_6(
              this,
              Invocation.getter(#limitBoxCoordinate),
            ),
          )
          as _i6.Rect);

  @override
  _i6.Rect get detectionFaceCoordinate =>
      (super.noSuchMethod(
            Invocation.getter(#detectionFaceCoordinate),
            returnValue: _FakeRect_6(
              this,
              Invocation.getter(#detectionFaceCoordinate),
            ),
          )
          as _i6.Rect);

  @override
  bool strictCornersInside() =>
      (super.noSuchMethod(
            Invocation.method(#strictCornersInside, []),
            returnValue: false,
          )
          as bool);

  @override
  bool centerInside() =>
      (super.noSuchMethod(
            Invocation.method(#centerInside, []),
            returnValue: false,
          )
          as bool);

  @override
  double overlapPercent() =>
      (super.noSuchMethod(
            Invocation.method(#overlapPercent, []),
            returnValue: 0.0,
          )
          as double);

  @override
  bool isFaceInsideBox({
    double? minOverlap = 0.5,
    bool? requireCenter = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#isFaceInsideBox, [], {
              #minOverlap: minOverlap,
              #requireCenter: requireCenter,
            }),
            returnValue: false,
          )
          as bool);
}

/// A class which mocks [CameraPlatform].
///
/// See the documentation for Mockito's code generation for more information.
class MockCameraPlatform extends _i1.Mock implements _i2.CameraPlatform {
  MockCameraPlatform() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<List<_i2.CameraDescription>> availableCameras() =>
      (super.noSuchMethod(
            Invocation.method(#availableCameras, []),
            returnValue: _i7.Future<List<_i2.CameraDescription>>.value(
              <_i2.CameraDescription>[],
            ),
          )
          as _i7.Future<List<_i2.CameraDescription>>);

  @override
  _i7.Future<int> createCamera(
    _i2.CameraDescription? cameraDescription,
    _i2.ResolutionPreset? resolutionPreset, {
    bool? enableAudio = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #createCamera,
              [cameraDescription, resolutionPreset],
              {#enableAudio: enableAudio},
            ),
            returnValue: _i7.Future<int>.value(0),
          )
          as _i7.Future<int>);

  @override
  _i7.Future<int> createCameraWithSettings(
    _i2.CameraDescription? cameraDescription,
    _i2.MediaSettings? mediaSettings,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createCameraWithSettings, [
              cameraDescription,
              mediaSettings,
            ]),
            returnValue: _i7.Future<int>.value(0),
          )
          as _i7.Future<int>);

  @override
  _i7.Future<void> initializeCamera(
    int? cameraId, {
    _i2.ImageFormatGroup? imageFormatGroup = _i2.ImageFormatGroup.unknown,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #initializeCamera,
              [cameraId],
              {#imageFormatGroup: imageFormatGroup},
            ),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Stream<_i2.CameraInitializedEvent> onCameraInitialized(int? cameraId) =>
      (super.noSuchMethod(
            Invocation.method(#onCameraInitialized, [cameraId]),
            returnValue: _i7.Stream<_i2.CameraInitializedEvent>.empty(),
          )
          as _i7.Stream<_i2.CameraInitializedEvent>);

  @override
  _i7.Stream<_i2.CameraResolutionChangedEvent> onCameraResolutionChanged(
    int? cameraId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#onCameraResolutionChanged, [cameraId]),
            returnValue: _i7.Stream<_i2.CameraResolutionChangedEvent>.empty(),
          )
          as _i7.Stream<_i2.CameraResolutionChangedEvent>);

  @override
  _i7.Stream<_i2.CameraClosingEvent> onCameraClosing(int? cameraId) =>
      (super.noSuchMethod(
            Invocation.method(#onCameraClosing, [cameraId]),
            returnValue: _i7.Stream<_i2.CameraClosingEvent>.empty(),
          )
          as _i7.Stream<_i2.CameraClosingEvent>);

  @override
  _i7.Stream<_i2.CameraErrorEvent> onCameraError(int? cameraId) =>
      (super.noSuchMethod(
            Invocation.method(#onCameraError, [cameraId]),
            returnValue: _i7.Stream<_i2.CameraErrorEvent>.empty(),
          )
          as _i7.Stream<_i2.CameraErrorEvent>);

  @override
  _i7.Stream<_i2.VideoRecordedEvent> onVideoRecordedEvent(int? cameraId) =>
      (super.noSuchMethod(
            Invocation.method(#onVideoRecordedEvent, [cameraId]),
            returnValue: _i7.Stream<_i2.VideoRecordedEvent>.empty(),
          )
          as _i7.Stream<_i2.VideoRecordedEvent>);

  @override
  _i7.Stream<_i2.DeviceOrientationChangedEvent> onDeviceOrientationChanged() =>
      (super.noSuchMethod(
            Invocation.method(#onDeviceOrientationChanged, []),
            returnValue: _i7.Stream<_i2.DeviceOrientationChangedEvent>.empty(),
          )
          as _i7.Stream<_i2.DeviceOrientationChangedEvent>);

  @override
  _i7.Future<void> lockCaptureOrientation(
    int? cameraId,
    _i8.DeviceOrientation? orientation,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lockCaptureOrientation, [cameraId, orientation]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> unlockCaptureOrientation(int? cameraId) =>
      (super.noSuchMethod(
            Invocation.method(#unlockCaptureOrientation, [cameraId]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<_i2.XFile> takePicture(int? cameraId) =>
      (super.noSuchMethod(
            Invocation.method(#takePicture, [cameraId]),
            returnValue: _i7.Future<_i2.XFile>.value(
              _FakeXFile_3(this, Invocation.method(#takePicture, [cameraId])),
            ),
          )
          as _i7.Future<_i2.XFile>);

  @override
  _i7.Future<void> prepareForVideoRecording() =>
      (super.noSuchMethod(
            Invocation.method(#prepareForVideoRecording, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> startVideoRecording(
    int? cameraId, {
    Duration? maxVideoDuration,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #startVideoRecording,
              [cameraId],
              {#maxVideoDuration: maxVideoDuration},
            ),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> startVideoCapturing(_i2.VideoCaptureOptions? options) =>
      (super.noSuchMethod(
            Invocation.method(#startVideoCapturing, [options]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<_i2.XFile> stopVideoRecording(int? cameraId) =>
      (super.noSuchMethod(
            Invocation.method(#stopVideoRecording, [cameraId]),
            returnValue: _i7.Future<_i2.XFile>.value(
              _FakeXFile_3(
                this,
                Invocation.method(#stopVideoRecording, [cameraId]),
              ),
            ),
          )
          as _i7.Future<_i2.XFile>);

  @override
  _i7.Future<void> pauseVideoRecording(int? cameraId) =>
      (super.noSuchMethod(
            Invocation.method(#pauseVideoRecording, [cameraId]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> resumeVideoRecording(int? cameraId) =>
      (super.noSuchMethod(
            Invocation.method(#resumeVideoRecording, [cameraId]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  bool supportsImageStreaming() =>
      (super.noSuchMethod(
            Invocation.method(#supportsImageStreaming, []),
            returnValue: false,
          )
          as bool);

  @override
  _i7.Stream<_i2.CameraImageData> onStreamedFrameAvailable(
    int? cameraId, {
    _i2.CameraImageStreamOptions? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #onStreamedFrameAvailable,
              [cameraId],
              {#options: options},
            ),
            returnValue: _i7.Stream<_i2.CameraImageData>.empty(),
          )
          as _i7.Stream<_i2.CameraImageData>);

  @override
  _i7.Future<void> setFlashMode(int? cameraId, _i2.FlashMode? mode) =>
      (super.noSuchMethod(
            Invocation.method(#setFlashMode, [cameraId, mode]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> setExposureMode(int? cameraId, _i2.ExposureMode? mode) =>
      (super.noSuchMethod(
            Invocation.method(#setExposureMode, [cameraId, mode]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> setExposurePoint(int? cameraId, _i12.Point<double>? point) =>
      (super.noSuchMethod(
            Invocation.method(#setExposurePoint, [cameraId, point]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<double> getMinExposureOffset(int? cameraId) =>
      (super.noSuchMethod(
            Invocation.method(#getMinExposureOffset, [cameraId]),
            returnValue: _i7.Future<double>.value(0.0),
          )
          as _i7.Future<double>);

  @override
  _i7.Future<double> getMaxExposureOffset(int? cameraId) =>
      (super.noSuchMethod(
            Invocation.method(#getMaxExposureOffset, [cameraId]),
            returnValue: _i7.Future<double>.value(0.0),
          )
          as _i7.Future<double>);

  @override
  _i7.Future<double> getExposureOffsetStepSize(int? cameraId) =>
      (super.noSuchMethod(
            Invocation.method(#getExposureOffsetStepSize, [cameraId]),
            returnValue: _i7.Future<double>.value(0.0),
          )
          as _i7.Future<double>);

  @override
  _i7.Future<double> setExposureOffset(int? cameraId, double? offset) =>
      (super.noSuchMethod(
            Invocation.method(#setExposureOffset, [cameraId, offset]),
            returnValue: _i7.Future<double>.value(0.0),
          )
          as _i7.Future<double>);

  @override
  _i7.Future<void> setFocusMode(int? cameraId, _i2.FocusMode? mode) =>
      (super.noSuchMethod(
            Invocation.method(#setFocusMode, [cameraId, mode]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> setFocusPoint(int? cameraId, _i12.Point<double>? point) =>
      (super.noSuchMethod(
            Invocation.method(#setFocusPoint, [cameraId, point]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<double> getMaxZoomLevel(int? cameraId) =>
      (super.noSuchMethod(
            Invocation.method(#getMaxZoomLevel, [cameraId]),
            returnValue: _i7.Future<double>.value(0.0),
          )
          as _i7.Future<double>);

  @override
  _i7.Future<double> getMinZoomLevel(int? cameraId) =>
      (super.noSuchMethod(
            Invocation.method(#getMinZoomLevel, [cameraId]),
            returnValue: _i7.Future<double>.value(0.0),
          )
          as _i7.Future<double>);

  @override
  _i7.Future<void> setZoomLevel(int? cameraId, double? zoom) =>
      (super.noSuchMethod(
            Invocation.method(#setZoomLevel, [cameraId, zoom]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> pausePreview(int? cameraId) =>
      (super.noSuchMethod(
            Invocation.method(#pausePreview, [cameraId]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> resumePreview(int? cameraId) =>
      (super.noSuchMethod(
            Invocation.method(#resumePreview, [cameraId]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> setDescriptionWhileRecording(
    _i2.CameraDescription? description,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#setDescriptionWhileRecording, [description]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i4.Widget buildPreview(int? cameraId) =>
      (super.noSuchMethod(
            Invocation.method(#buildPreview, [cameraId]),
            returnValue: _FakeWidget_4(
              this,
              Invocation.method(#buildPreview, [cameraId]),
            ),
          )
          as _i4.Widget);

  @override
  _i7.Future<void> dispose(int? cameraId) =>
      (super.noSuchMethod(
            Invocation.method(#dispose, [cameraId]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> setImageFileFormat(
    int? cameraId,
    _i2.ImageFileFormat? format,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#setImageFileFormat, [cameraId, format]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);
}
